on:
  push:
    branches:
        - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
jobs:
    init:
      runs-on: ubuntu-latest
      steps:
         - name: clone repo
           uses: action/checkout@v4
         - name: Install terraform
           uses: hashicorp/Setup-terraforn@v3
           with:
             terraform_version: "1.1.7"
         - name: init
           run: terraform init
         - name: format
           run: terraform fmt
         - name: plan
           run: terraform plan
         - name: run checkov
           if: success()
           uses: bridgecrewio/checkov-action@master
           with:
            output_format: cli,sarif
            output_file_path: console,results.sarif
         - name: plan
           if: success()
           run: terraform apply -auto-approve
